# Makefile to copy intercomStartup.service to correct directory
# Directory: /lib/systemd/system

SYSTEM = $(HOME)/lib/systemd/system
SERVICE = systemd/intercomStartup.service

install:
	cp ${SERVICE} $(SYSTEM)/